"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const CampaignController_1 = require("../controllers/CampaignController");
const CampaignPlayerController_1 = require("../controllers/CampaignPlayerController");
const RoomCampaignController_1 = require("../controllers/RoomCampaignController");
const RoomController_1 = require("../controllers/RoomController");
const ReviewController_1 = require("../controllers/ReviewController");
const router = (0, express_1.Router)();
router.post('/room', RoomController_1.RoomController.createRoom);
router.get('/rooms', RoomController_1.RoomController.getRooms);
router.get('/room/:id', RoomController_1.RoomController.getRoom);
router.put('/room/:id', RoomController_1.RoomController.updateRoom);
router.delete('/room/:id', RoomController_1.RoomController.deleteRoom);
router.post('/room/:id/campaign', RoomCampaignController_1.RoomCampaignController.createCampaign);
router.get('/room/:id/campaigns', RoomCampaignController_1.RoomCampaignController.getCampaigns);
router.get('campaigns', CampaignController_1.CampaignController.getCampaign);
router.get('campaign/:id', CampaignController_1.CampaignController.getCampaign);
router.put('campaign/:id', CampaignController_1.CampaignController.updateCampaign);
router.delete('campaign/:id', CampaignController_1.CampaignController.deleteCampaign);
router.post('campaign/:id/review', ReviewController_1.ReviewController.createReview);
router.get('campaign/:id/reviews', ReviewController_1.ReviewController.getReviews);
router.get('campaign/:id/review/:id', ReviewController_1.ReviewController.getReview);
router.put('campaign/:id/review/:id', ReviewController_1.ReviewController.updateReview);
router.delete('campaign/:id/review/:id', ReviewController_1.ReviewController.deleteReview);
router.post('campaign/:campaignId/player', CampaignPlayerController_1.CampaignPlayerController.createPlayer);
router.get('campaign/:campaignId/players', CampaignPlayerController_1.CampaignPlayerController.getPlayers);
router.get('campaign/:campaignId/player/:playerId', CampaignPlayerController_1.CampaignPlayerController.getPlayer);
router.delete('campaign/:campaignId/player/:playerId', CampaignPlayerController_1.CampaignPlayerController.deletePlayer);
exports.default = router;
//# sourceMappingURL=index.js.map